finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('birds/', views.finch_index, name='index'),
    path('birds/<int:bird_id>/', views.birds_detail, name='detail'),
    path('birds/create/', views.FinchCreate.as_view(), name='finch_create'),
    path('birds/<int:pk>/update/', views.FinchUpdate.as_view(), name='finch_update'),
    path('birds/<int:pk>/delete/', views.FinchDelete.as_view(), name='finch_delete'),
    path('birds/<int:bird_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('cats/<int:bird_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('cats/<int:bird_id>/unassoc_toy/<int:toy_id>/', views.unassoc_toy, name='unassoc_toy'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
]

main_app/models.py
from django.db import models

from django.urls import reverse

# Create your models here.

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Toy(models.Model):
   name = models.CharField(max_length=50)
   color = models.CharField(max_length=20)

   def __str__(self):
      return self.name
   
   def get_absolute_url(self):
      return reverse('toys_detail', kwargs={'pk': self.id})

class Bird(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)
    
    def __str__(self):
        return f'{self.name} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'bird_id': self.id})
    
class Feeding(models.Model):
  date = models.DateField('feeding date')
  meal = models.CharField(
      max_length=1,
      choices=MEALS,
      default=MEALS[0][0]
    )
  bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_meal_display()} on {self.date}"
  class Meta:
     ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Bird, Toy
from .forms import FeedingForm
# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def finch_index(request, bird_id):
    birds = Bird.objects(id=bird_id)
    return render(request, 'birds/index.html', {'birds': birds,})

def birds_detail(request, bird_id):
    bird = Bird.objects.get(id=bird_id)
    id_list = bird.toys.all().values_list('id')
    toys_bird_doesnt_have = Toy.objects.exclude(id__in=id_list)
    feeding_form = FeedingForm()
    feeding_form = FeedingForm()
    return render(request, 'birds/detail.html', {
       'bird': bird, 
       'feeding_form': feeding_form,
       'toys': toys_bird_doesnt_have
        })

class FinchCreate(CreateView):
    model = Bird
    fields = ['name', 'breed', 'description', 'age']

class FinchUpdate(UpdateView):
    model = Bird
    fields = ['breed', 'description', 'age']

class FinchDelete(DeleteView):
    model = Bird
    success_url = '/birds'

def add_feeding(request, bird_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.bird_id = bird_id
        new_feeding.save()
    return redirect('detail', bird_id=bird_id)

class ToyList(ListView):
  model = Toy

class ToyDetail(DetailView):
  model = Toy

class ToyCreate(CreateView):
  model = Toy
  fields = '__all__'

class ToyUpdate(UpdateView):
  model = Toy
  fields = ['name', 'color']

class ToyDelete(DeleteView):
  model = Toy
  success_url = '/toys'

def assoc_toy(request, bird_id, toy_id):
   Bird.objects.get(id=bird_id).toys.add(toy_id)
   return redirect('detail', bird_id=bird_id)

def unassoc_toy(request, bird_id, toy_id):
   Bird.objects.get(id=bird_id).toys.remove(toy_id)
   return redirect('detail', bird_id=bird_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome to Finch Collector</h1>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Finch Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Finch Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
          <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
          <li><a href="{% url 'finch_create' %}">Add A Bird</a></li>
          <li><a href="{% url 'index' %}">View All My Birds</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2024 Finch Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/birds/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch List</h1>

<div class="card">
  <div class="card-content">
  <span class="card-title">{{ bird.name }}</span>
  <p>Breed: {{ bird.breed }}</p>
  <p>Description: {{ bird.description }}</p>
      <p>Age In Months: {{ bird.age }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'finch_update' bird.id %}">Edit</a>
    <a href="{% url 'finch_delete' bird.id %}">Delete</a>
  </div>
</div>
<div class="col s6">
  <form action="{% url 'add_feeding' bird.id %}" method="POST">
    {% csrf_token %}
    {{ feeding_form.as_p }}
    <input type="submit" class="btn" value="Add Feeding">
  </form>
  <table class="striped">
    <thead>
      <tr><th>Date</th><th>Meal</th></tr>
    </thead>
    <tbody>
      {% for feeding in bird.feeding_set.all %}
        <tr>
          <td>{{feeding.date}}</td>
          <td>{{feeding.get_meal_display}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ bird.name }}'s Toys</h3>
    {% if bird.toys.count %}
      {% for toy in bird.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
            <div class="card-action">
              <form action="{% url 'unassoc_toy' bird.id toy.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">Remove</button>
              </form>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Toys</h5>
    {% endif %}
  </div>
</div>
<div class="col s6">
  <h3>Available Toys</h3>
  {% if toys.count %}
    {% for toy in toys.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
          </span>
          <div class="card-action">
            <form action="{% url 'assoc_toy' bird.id toy.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <h5>{{bird.name}} Already Has All Toys Available</h5>
  {% endif %}
</div>

<script>
    const dateEl = document.getElementById('id_date');
    // M is Materialize's global variable
    M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/birds/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch List</h1>

{% for bird in birds %}
  <div class="card">
    <a href="{% url 'detail' bird.id %}">
      <div class="card-content">
        <span class="card-title">{{ bird.name }}</span>
        <p>Breed: {{ bird.breed }}</p>
        <p>Description: {{ bird.description }}</p>
          <p>Age In Months: {{ bird.age }}</p>
      </div>
    </a>
    <div class="card-action">
      <a href="{% url 'finch_update' bird.id %}">Edit</a>
      <a href="{% url 'finch_delete' bird.id %}">Delete</a>
    </div>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Home</h1>
{% endblock %}

main_app/templates/main_app/bird_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Cat</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' bird.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/bird_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Finch</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'toys_update' toy.id %}">Edit</a>
        <a href="{% url 'toys_delete' toy.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Toy</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy List</h1>

{% for toy in toy_list %}
  <a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}